language: swift
osx_image: xcode11.3

branches:
    only:
    - master

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap --platform iOS

script:
- set -o pipefail && xcodebuild -project ReadabilityKit.xcodeproj -scheme 'ReadabilityKit iOS' -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' | xcpretty;
